language:
  - R

r:
  - devel

sudo:
  - FALSE

warnings_are_errors:
  - true

# r_build_args:
#   - '--no-build-vignettes'

# r_check_args:
#   - '--ignore-vignettes'

before_install:
  - chmod 755 ./travis_tool/travis_timeout.sh

script:
  - ./travis_tool/travis_timeout.sh travis_wait

# r_packages:
#   - pkgdown

r_github_packages:
  - covr

after_success:
  - travis_wait 30
  - Rscript -e 'covr::codecov()'
  # - Rscript -e 'devtools::install()'
  # - Rscript -e 'pkgdown::build_site()'

notifications:
  email:
    on_success: change
    on_failure: always

before_cache:
  - Rscript -e 'remotes::install_cran("pkgdown")'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
